import '../models/flavor.dart';

class FlavorConfigGenerator {
  static String generate(List<Flavor> flavors) {
    final names = flavors.map((f) => f.name).join(', ');
    final getters = flavors
        .map((f) => '  bool get is${_cap(f.name)} => flavor == AppFlavor.${f.name};')
        .join('\n');
    return '''
// GENERATED BY flutter_flavor_gen — DO NOT EDIT MANUALLY
import 'flavor_values.dart';

enum AppFlavor { $names }

class FlavorConfig {
  final AppFlavor flavor;
  final FlavorValues values;
  static FlavorConfig? _instance;

  FlavorConfig._({required this.flavor, required this.values});

  factory FlavorConfig({required AppFlavor flavor, required FlavorValues values}) {
    _instance = FlavorConfig._(flavor: flavor, values: values);
    return _instance!;
  }

  static FlavorConfig get instance {
    assert(_instance != null, 'FlavorConfig has not been initialized.');
    return _instance!;
  }

$getters
}
''';
  }

  static String _cap(String s) => s[0].toUpperCase() + s.substring(1);
}