import '../models/flavor.dart';

class FlavorValuesGenerator {
  static String generate(List<Flavor> flavors) {
    final params = flavors.first.parameters;
    final fields = params.map((p) => '  final ${p.type} ${p.name};').join('\n');
    final ctor = params.map((p) => '    required this.${p.name},').join('\n');
    return '''
// GENERATED BY flutter_flavor_gen — DO NOT EDIT MANUALLY
class FlavorValues {
$fields

  const FlavorValues({
$ctor
  });
}
''';
  }
}