import '../models/flavor.dart';

class MainGenerator {
  static String generate(Flavor flavor) {
    final args = flavor.parameters
        .map((p) => p.type == 'String'
            ? "      ${p.name}: '${p.value}',"
            : '      ${p.name}: ${p.value},')
        .join('\n');
    return '''
// GENERATED BY flutter_flavor_gen — DO NOT EDIT MANUALLY
import 'flavors/flavor_config.dart';
import 'flavors/flavor_values.dart';
import 'main_common.dart';

void main() {
  FlavorConfig(
    flavor: AppFlavor.${flavor.name},
    values: FlavorValues(
$args
    ),
  );
  mainCommon();
}
''';
  }
}